apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywarapp-deploy
  labels:
    app: mywarapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywarapp
  template:
    metadata:
      labels:
        app: mywarapp
    spec:
      containers:
        - name: mywarapp
          image: nsbyadav14e/loginpage:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mywarapp-service
spec:
  type: LoadBalancer
  selector:
    app: mywarapp
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
