apiVersion: apps/v1
kind: Deployment
metadata:
  name: flip-deployment
  labels:
    app: mywarapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flip-app
  template:
    metadata:
      labels:
        app: flip-app
    spec:
      containers:
        - name: mywarapp
          image: nsbyadav14e/flip01:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mywarapp-service
spec:
  type: LoadBalancer
  selector:
    app: flip-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
